[rospy.client][INFO] 2022-01-06 23:02:00,520: init_node, name[/brain_17827_1641490320483], pid[17827]
[xmlrpc][INFO] 2022-01-06 23:02:00,520: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-01-06 23:02:00,520: Started XML-RPC server [http://prajwal-IdeaPad-L340-15IRH-Gaming:39395/]
[rospy.init][INFO] 2022-01-06 23:02:00,520: ROS Slave URI: [http://prajwal-IdeaPad-L340-15IRH-Gaming:39395/]
[rospy.impl.masterslave][INFO] 2022-01-06 23:02:00,521: _ready: http://prajwal-IdeaPad-L340-15IRH-Gaming:39395/
[rospy.registration][INFO] 2022-01-06 23:02:00,521: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2022-01-06 23:02:00,521: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2022-01-06 23:02:00,621: registered with master
[rospy.rosout][INFO] 2022-01-06 23:02:00,621: initializing /rosout core topic
[rospy.rosout][INFO] 2022-01-06 23:02:00,623: connected to core topic /rosout
[rospy.simtime][INFO] 2022-01-06 23:02:00,624: initializing /clock core topic
[rospy.simtime][INFO] 2022-01-06 23:02:00,625: connected to core topic /clock
[rospy.internal][INFO] 2022-01-06 23:02:00,626: topic[/clock] adding connection to [http://prajwal-IdeaPad-L340-15IRH-Gaming:34133/], count 0
[rospy.internal][INFO] 2022-01-06 23:02:00,633: topic[/grid3/allRobots/poses] adding connection to [http://prajwal-IdeaPad-L340-15IRH-Gaming:35553/], count 0
[rospy.internal][INFO] 2022-01-06 23:02:00,635: topic[/grid3/planner/status] adding connection to [http://prajwal-IdeaPad-L340-15IRH-Gaming:44373/], count 0
[rospy.internal][INFO] 2022-01-06 23:02:00,637: topic[/grid3/packageLoaded] adding connection to [http://prajwal-IdeaPad-L340-15IRH-Gaming:46329/], count 0
[rospy.internal][INFO] 2022-01-06 23:02:00,637: topic[/grid3/droppingCompleted] adding connection to [http://prajwal-IdeaPad-L340-15IRH-Gaming:46329/], count 0
[rospy.internal][INFO] 2022-01-06 23:02:00,696: topic[/grid3/allRobots/goals] adding connection to [/trajectory_planner], count 0
[rospy.internal][INFO] 2022-01-06 23:02:00,892: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2022-01-06 23:02:01,498: topic[/grid3/droppingCompleted] adding connection to [http://prajwal-IdeaPad-L340-15IRH-Gaming:34451/], count 1
[rospy.internal][INFO] 2022-01-06 23:02:01,499: topic[/grid3/packageLoaded] adding connection to [http://prajwal-IdeaPad-L340-15IRH-Gaming:34451/], count 1
[rospy.internal][ERROR] 2022-01-06 23:04:49,988: Unable to initiate TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:35617 (http://prajwal-IdeaPad-L340-15IRH-Gaming:46329/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: [/rqt_gui_py_node_17678] is not a publisher of [/grid3/droppingCompleted]. Topics are [['/rosout', 'rosgraph_msgs/Log'], ['/grid3/packageLoaded', 'grid3/packageLoaded'], ['/robot1/cmd_ve', 'geometry_msgs/Twist'], ['/robot2/cmd_ve', 'geometry_msgs/Twist'], ['/robot3/cmd_ve', 'geometry_msgs/Twist'], ['/robot4/cmd_ve', 'geometry_msgs/Twist']]

[rospy.internal][ERROR] 2022-01-06 23:04:49,992: Unable to initiate TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:35617 (http://prajwal-IdeaPad-L340-15IRH-Gaming:46329/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: [/rqt_gui_py_node_17678] is not a publisher of [/grid3/packageLoaded]. Topics are [['/rosout', 'rosgraph_msgs/Log'], ['/robot1/cmd_ve', 'geometry_msgs/Twist'], ['/robot2/cmd_ve', 'geometry_msgs/Twist'], ['/robot3/cmd_ve', 'geometry_msgs/Twist'], ['/robot4/cmd_ve', 'geometry_msgs/Twist']]

[rospy.internal][WARNING] 2022-01-06 23:04:50,990: Unknown error initiating TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:35617 (http://prajwal-IdeaPad-L340-15IRH-Gaming:46329/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
ConnectionRefusedError: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-01-06 23:04:50,990: topic[/grid3/droppingCompleted] removing connection to http://prajwal-IdeaPad-L340-15IRH-Gaming:46329/
[rospy.internal][WARNING] 2022-01-06 23:04:50,993: Unknown error initiating TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:35617 (http://prajwal-IdeaPad-L340-15IRH-Gaming:46329/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
ConnectionRefusedError: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-01-06 23:04:50,994: topic[/grid3/packageLoaded] removing connection to http://prajwal-IdeaPad-L340-15IRH-Gaming:46329/
[rospy.internal][ERROR] 2022-01-06 23:16:41,131: Unable to initiate TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:35335 (http://prajwal-IdeaPad-L340-15IRH-Gaming:34133/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 35335 to [127.0.0.1:50226 on socket 17]] [/brain_17827_1641490320483].

[rospy.internal][ERROR] 2022-01-06 23:16:41,798: Unable to initiate TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:46735 (http://prajwal-IdeaPad-L340-15IRH-Gaming:35553/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2022-01-06 23:16:41,799: Unable to initiate TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:41853 (http://prajwal-IdeaPad-L340-15IRH-Gaming:44373/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2022-01-06 23:16:41,812: Unable to initiate TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:39673 (http://prajwal-IdeaPad-L340-15IRH-Gaming:34451/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: [/rqt_gui] is not a publisher of [/grid3/droppingCompleted]. Topics are [['/rosout', 'rosgraph_msgs/Log'], ['/grid3/packageLoaded', 'grid3/packageLoaded'], ['/robot1/cmd_ve', 'geometry_msgs/Twist'], ['/robot2/cmd_ve', 'geometry_msgs/Twist'], ['/robot3/cmd_ve', 'geometry_msgs/Twist'], ['/robot4/cmd_ve', 'geometry_msgs/Twist']]

[rospy.internal][ERROR] 2022-01-06 23:16:41,814: Unable to initiate TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:39673 (http://prajwal-IdeaPad-L340-15IRH-Gaming:34451/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: [/rqt_gui] is not a publisher of [/grid3/packageLoaded]. Topics are [['/rosout', 'rosgraph_msgs/Log'], ['/robot1/cmd_ve', 'geometry_msgs/Twist'], ['/robot2/cmd_ve', 'geometry_msgs/Twist'], ['/robot3/cmd_ve', 'geometry_msgs/Twist'], ['/robot4/cmd_ve', 'geometry_msgs/Twist']]

[rospy.internal][WARNING] 2022-01-06 23:16:42,133: Unknown error initiating TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:35335 (http://prajwal-IdeaPad-L340-15IRH-Gaming:34133/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
ConnectionRefusedError: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-01-06 23:16:42,133: topic[/clock] removing connection to http://prajwal-IdeaPad-L340-15IRH-Gaming:34133/
[rospy.internal][INFO] 2022-01-06 23:16:42,254: topic[/grid3/allRobots/goals] removing connection to /trajectory_planner
[rospy.internal][WARNING] 2022-01-06 23:16:42,800: Unknown error initiating TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:46735 (http://prajwal-IdeaPad-L340-15IRH-Gaming:35553/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
ConnectionRefusedError: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-01-06 23:16:42,800: topic[/grid3/allRobots/poses] removing connection to http://prajwal-IdeaPad-L340-15IRH-Gaming:35553/
[rospy.internal][WARNING] 2022-01-06 23:16:42,804: Unknown error initiating TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:41853 (http://prajwal-IdeaPad-L340-15IRH-Gaming:44373/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2022-01-06 23:16:42,805: topic[/grid3/planner/status] removing connection to http://prajwal-IdeaPad-L340-15IRH-Gaming:44373/
[rospy.internal][WARNING] 2022-01-06 23:16:42,813: Unknown error initiating TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:39673 (http://prajwal-IdeaPad-L340-15IRH-Gaming:34451/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
ConnectionRefusedError: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-01-06 23:16:42,814: topic[/grid3/droppingCompleted] removing connection to http://prajwal-IdeaPad-L340-15IRH-Gaming:34451/
[rospy.internal][WARNING] 2022-01-06 23:16:42,815: Unknown error initiating TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:39673 (http://prajwal-IdeaPad-L340-15IRH-Gaming:34451/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
ConnectionRefusedError: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-01-06 23:16:42,815: topic[/grid3/packageLoaded] removing connection to http://prajwal-IdeaPad-L340-15IRH-Gaming:34451/
[rospy.internal][INFO] 2022-01-06 23:16:56,262: topic[/rosout] removing connection to /rosout
