[rospy.client][INFO] 2022-01-08 13:53:50,987: init_node, name[/brain_35280_1641630230955], pid[35280]
[xmlrpc][INFO] 2022-01-08 13:53:50,987: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-01-08 13:53:50,987: Started XML-RPC server [http://prajwal-IdeaPad-L340-15IRH-Gaming:33291/]
[rospy.impl.masterslave][INFO] 2022-01-08 13:53:50,987: _ready: http://prajwal-IdeaPad-L340-15IRH-Gaming:33291/
[rospy.init][INFO] 2022-01-08 13:53:50,987: ROS Slave URI: [http://prajwal-IdeaPad-L340-15IRH-Gaming:33291/]
[rospy.registration][INFO] 2022-01-08 13:53:50,988: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2022-01-08 13:53:50,988: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2022-01-08 13:53:51,088: registered with master
[rospy.rosout][INFO] 2022-01-08 13:53:51,088: initializing /rosout core topic
[rospy.rosout][INFO] 2022-01-08 13:53:51,090: connected to core topic /rosout
[rospy.simtime][INFO] 2022-01-08 13:53:51,091: initializing /clock core topic
[rospy.simtime][INFO] 2022-01-08 13:53:51,092: connected to core topic /clock
[rospy.internal][INFO] 2022-01-08 13:53:51,093: topic[/clock] adding connection to [http://prajwal-IdeaPad-L340-15IRH-Gaming:37677/], count 0
[rospy.internal][INFO] 2022-01-08 13:53:51,098: topic[/grid3/allRobots/poses] adding connection to [http://prajwal-IdeaPad-L340-15IRH-Gaming:32987/], count 0
[rospy.internal][INFO] 2022-01-08 13:53:51,101: topic[/grid3/planner/status] adding connection to [http://prajwal-IdeaPad-L340-15IRH-Gaming:34867/], count 0
[rospy.internal][INFO] 2022-01-08 13:53:51,110: topic[/grid3/allRobots/goals] adding connection to [/trajectory_planner], count 0
[rospy.internal][INFO] 2022-01-08 13:53:51,308: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2022-01-08 13:53:52,011: topic[/grid3/droppingCompleted] adding connection to [http://prajwal-IdeaPad-L340-15IRH-Gaming:39225/], count 0
[rospy.internal][INFO] 2022-01-08 13:53:52,013: topic[/grid3/packageLoaded] adding connection to [http://prajwal-IdeaPad-L340-15IRH-Gaming:39225/], count 0
[rospy.internal][ERROR] 2022-01-08 14:00:53,241: Unable to initiate TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:43781 (http://prajwal-IdeaPad-L340-15IRH-Gaming:34867/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2022-01-08 14:00:53,243: topic[/grid3/allRobots/goals] adding connection to [/trajectory_planner], count 1
[rospy.internal][INFO] 2022-01-08 14:00:53,244: topic[/grid3/allRobots/goals] removing connection to /trajectory_planner
[rospy.internal][ERROR] 2022-01-08 14:00:53,245: Unable to initiate TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:37647 (http://prajwal-IdeaPad-L340-15IRH-Gaming:32987/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2022-01-08 14:00:53,250: Unable to initiate TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:32841 (http://prajwal-IdeaPad-L340-15IRH-Gaming:39225/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: [/rqt_gui] is not a publisher of [/grid3/droppingCompleted]. Topics are [['/rosout', 'rosgraph_msgs/Log'], ['/robot1/cmd_vel', 'geometry_msgs/Twist'], ['/robot2/cmd_vel', 'geometry_msgs/Twist'], ['/robot3/cmd_vel', 'geometry_msgs/Twist'], ['/robot4/cmd_ve', 'geometry_msgs/Twist']]

[rospy.internal][ERROR] 2022-01-08 14:00:53,255: Unable to initiate TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:32841 (http://prajwal-IdeaPad-L340-15IRH-Gaming:39225/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: [/rqt_gui] is not a publisher of [/grid3/packageLoaded]. Topics are [['/rosout', 'rosgraph_msgs/Log'], ['/robot2/cmd_vel', 'geometry_msgs/Twist'], ['/robot3/cmd_vel', 'geometry_msgs/Twist'], ['/robot4/cmd_ve', 'geometry_msgs/Twist']]

[rospy.internal][INFO] 2022-01-08 14:00:53,654: topic[/grid3/allRobots/goals] removing connection to /trajectory_planner
[rospy.internal][WARNING] 2022-01-08 14:00:54,243: Unknown error initiating TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:43781 (http://prajwal-IdeaPad-L340-15IRH-Gaming:34867/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
ConnectionRefusedError: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-01-08 14:00:54,243: topic[/grid3/planner/status] removing connection to http://prajwal-IdeaPad-L340-15IRH-Gaming:34867/
[rospy.internal][WARNING] 2022-01-08 14:00:54,251: Unknown error initiating TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:32841 (http://prajwal-IdeaPad-L340-15IRH-Gaming:39225/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
ConnectionRefusedError: [Errno 111] Connection refused

[rospy.internal][WARNING] 2022-01-08 14:00:54,252: Unknown error initiating TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:37647 (http://prajwal-IdeaPad-L340-15IRH-Gaming:32987/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2022-01-08 14:00:54,252: topic[/grid3/droppingCompleted] removing connection to http://prajwal-IdeaPad-L340-15IRH-Gaming:39225/
[rospy.internal][INFO] 2022-01-08 14:00:54,252: topic[/grid3/allRobots/poses] removing connection to http://prajwal-IdeaPad-L340-15IRH-Gaming:32987/
[rospy.internal][WARNING] 2022-01-08 14:00:54,257: Unknown error initiating TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:32841 (http://prajwal-IdeaPad-L340-15IRH-Gaming:39225/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
ConnectionRefusedError: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-01-08 14:00:54,257: topic[/grid3/packageLoaded] removing connection to http://prajwal-IdeaPad-L340-15IRH-Gaming:39225/
[rospy.internal][ERROR] 2022-01-08 14:00:55,531: Unable to initiate TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:56887 (http://prajwal-IdeaPad-L340-15IRH-Gaming:37677/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 56887 to [127.0.0.1:60064 on socket 18]] [/brain_35280_1641630230955].

[rospy.internal][WARNING] 2022-01-08 14:00:56,532: Unknown error initiating TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:56887 (http://prajwal-IdeaPad-L340-15IRH-Gaming:37677/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
ConnectionRefusedError: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-01-08 14:00:56,532: topic[/clock] removing connection to http://prajwal-IdeaPad-L340-15IRH-Gaming:37677/
[rospy.internal][INFO] 2022-01-08 14:01:11,162: topic[/rosout] removing connection to /rosout
