[rospy.client][INFO] 2022-01-08 13:04:22,867: init_node, name[/controller_ros_interface_29451_1641627262840], pid[29451]
[xmlrpc][INFO] 2022-01-08 13:04:22,867: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-01-08 13:04:22,867: Started XML-RPC server [http://prajwal-IdeaPad-L340-15IRH-Gaming:33565/]
[rospy.impl.masterslave][INFO] 2022-01-08 13:04:22,868: _ready: http://prajwal-IdeaPad-L340-15IRH-Gaming:33565/
[rospy.init][INFO] 2022-01-08 13:04:22,868: ROS Slave URI: [http://prajwal-IdeaPad-L340-15IRH-Gaming:33565/]
[rospy.registration][INFO] 2022-01-08 13:04:22,868: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2022-01-08 13:04:22,868: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2022-01-08 13:04:22,968: registered with master
[rospy.rosout][INFO] 2022-01-08 13:04:22,968: initializing /rosout core topic
[rospy.rosout][INFO] 2022-01-08 13:04:22,974: connected to core topic /rosout
[rospy.simtime][INFO] 2022-01-08 13:04:22,976: initializing /clock core topic
[rospy.simtime][INFO] 2022-01-08 13:04:22,980: connected to core topic /clock
[rospy.internal][INFO] 2022-01-08 13:04:22,984: topic[/clock] adding connection to [http://prajwal-IdeaPad-L340-15IRH-Gaming:41297/], count 0
[rospy.internal][INFO] 2022-01-08 13:04:22,999: topic[/grid3/allRobots/poses] adding connection to [http://prajwal-IdeaPad-L340-15IRH-Gaming:41809/], count 0
[rospy.internal][INFO] 2022-01-08 13:04:23,006: topic[/grid3/robotTrajectories] adding connection to [http://prajwal-IdeaPad-L340-15IRH-Gaming:35423/], count 0
[rospy.internal][INFO] 2022-01-08 13:04:23,009: topic[/grid3/planner/status] adding connection to [http://prajwal-IdeaPad-L340-15IRH-Gaming:35423/], count 0
[rospy.internal][INFO] 2022-01-08 13:04:23,133: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][ERROR] 2022-01-08 13:09:07,795: Unable to initiate TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:35307 (http://prajwal-IdeaPad-L340-15IRH-Gaming:35423/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2022-01-08 13:09:07,797: Unable to initiate TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:35307 (http://prajwal-IdeaPad-L340-15IRH-Gaming:35423/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2022-01-08 13:09:07,797: Unable to initiate TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:35733 (http://prajwal-IdeaPad-L340-15IRH-Gaming:41809/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: node shutting down

[rospy.core][INFO] 2022-01-08 13:09:08,190: signal_shutdown [signal-2]
[rospy.internal][INFO] 2022-01-08 13:09:08,192: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2022-01-08 13:09:08,192: topic[/clock] removing connection to http://prajwal-IdeaPad-L340-15IRH-Gaming:41297/
[rospy.internal][INFO] 2022-01-08 13:09:08,192: topic[/grid3/allRobots/poses] removing connection to http://prajwal-IdeaPad-L340-15IRH-Gaming:41809/
[rospy.internal][INFO] 2022-01-08 13:09:08,192: topic[/grid3/robotTrajectories] removing connection to http://prajwal-IdeaPad-L340-15IRH-Gaming:35423/
[rospy.internal][INFO] 2022-01-08 13:09:08,192: topic[/grid3/planner/status] removing connection to http://prajwal-IdeaPad-L340-15IRH-Gaming:35423/
[rospy.impl.masterslave][INFO] 2022-01-08 13:09:08,192: signal-2
[rospy.core][INFO] 2022-01-08 13:09:09,221: signal_shutdown [atexit]
