[rospy.client][INFO] 2022-01-07 16:35:09,098: init_node, name[/display_map], pid[15978]
[xmlrpc][INFO] 2022-01-07 16:35:09,099: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-01-07 16:35:09,099: Started XML-RPC server [http://prajwal-IdeaPad-L340-15IRH-Gaming:46127/]
[rospy.init][INFO] 2022-01-07 16:35:09,099: ROS Slave URI: [http://prajwal-IdeaPad-L340-15IRH-Gaming:46127/]
[rospy.impl.masterslave][INFO] 2022-01-07 16:35:09,099: _ready: http://prajwal-IdeaPad-L340-15IRH-Gaming:46127/
[rospy.registration][INFO] 2022-01-07 16:35:09,100: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2022-01-07 16:35:09,100: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2022-01-07 16:35:09,199: registered with master
[rospy.rosout][INFO] 2022-01-07 16:35:09,199: initializing /rosout core topic
[rospy.rosout][INFO] 2022-01-07 16:35:09,202: connected to core topic /rosout
[rospy.simtime][INFO] 2022-01-07 16:35:09,202: initializing /clock core topic
[rospy.simtime][INFO] 2022-01-07 16:35:09,203: connected to core topic /clock
[rospy.internal][INFO] 2022-01-07 16:35:09,204: topic[/clock] adding connection to [http://prajwal-IdeaPad-L340-15IRH-Gaming:38951/], count 0
[rospy.internal][INFO] 2022-01-07 16:35:09,456: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2022-01-07 16:35:09,956: topic[/grid3/mat] adding connection to [/rviz], count 0
[rospy.internal][ERROR] 2022-01-07 16:41:57,140: Unable to initiate TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:45573 (http://prajwal-IdeaPad-L340-15IRH-Gaming:38951/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 45573 to [127.0.0.1:46336 on socket 18]] [/display_map].

[rospy.internal][WARNING] 2022-01-07 16:41:58,141: Unknown error initiating TCP/IP socket to prajwal-IdeaPad-L340-15IRH-Gaming:45573 (http://prajwal-IdeaPad-L340-15IRH-Gaming:38951/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
ConnectionRefusedError: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-01-07 16:41:58,142: topic[/clock] removing connection to http://prajwal-IdeaPad-L340-15IRH-Gaming:38951/
[rospy.core][INFO] 2022-01-07 16:41:59,145: signal_shutdown [signal-2]
[rospy.internal][INFO] 2022-01-07 16:41:59,148: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2022-01-07 16:41:59,148: topic[/grid3/mat] removing connection to /rviz
[rospy.impl.masterslave][INFO] 2022-01-07 16:41:59,148: signal-2
[rospy.core][INFO] 2022-01-07 16:42:01,269: signal_shutdown [atexit]
